# -*- coding: utf-8 -*-
"""Team 1 Project complete

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1afTAXTmg8BecFK-nmtgxbzcOAAGRrV7j
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("joniarroba/noshowappointments")

print("Path to dataset files:", path)
import os

# ==========================================
# HEALTHCARE & TELEMEDICINE EDA PROJECT
# ==========================================

# Import Libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

from scipy.stats import (
    boxcox,
    chi2_contingency,
    f_oneway,
    skew
)

# ==========================================
# LOAD DATASET
# ==========================================

df = pd.read_csv(os.path.join(path, "KaggleV2-May-2016.csv"))
df.head()

print("="*50)
print("DATASET SHAPE")
print("="*50)
print(df.shape)

# ==========================================
# DATA UNDERSTANDING
# ==========================================

print("\nFIRST 5 RECORDS")
print(df.head())

print("\nDATA INFORMATION")
print(df.info())

print("\nSTATISTICAL SUMMARY")
print(df.describe())

# ==========================================
# MISSING VALUES
# ==========================================

print("\nMISSING VALUES")
print(df.isnull().sum())

# ==========================================
# DUPLICATES
# ==========================================

print("\nDUPLICATE RECORDS")
print(df.duplicated().sum())

# ==========================================
# DATETIME CONVERSION
# ==========================================

df['ScheduledDay'] = pd.to_datetime(df['ScheduledDay'])
df['AppointmentDay'] = pd.to_datetime(df['AppointmentDay'])

# ==========================================
# FEATURE ENGINEERING
# WAITING TIME
# ==========================================

df['Waiting_Time'] = (
    df['AppointmentDay'] - df['ScheduledDay']
).dt.days

# Remove negative waiting times

df['Waiting_Time'] = df['Waiting_Time'].clip(lower=0)

# ==========================================
# OUTLIER ANALYSIS (AGE)
# ==========================================

Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df['Age'] < lower) |
    (df['Age'] > upper)
]

print("\nNUMBER OF AGE OUTLIERS")
print(len(outliers))

plt.figure(figsize=(6,4))
sns.boxplot(x=df['Age'])
plt.title("Age Outlier Detection")
plt.show()

# ==========================================
# DISTRIBUTION ANALYSIS
# ==========================================

plt.figure(figsize=(8,5))
sns.histplot(df['Age'], kde=True)
plt.title("Age Distribution")
plt.show()

# ==========================================
# LOG TRANSFORMATION
# ==========================================

# Ensure Waiting_Time is non-negative before transformation
df['Waiting_Time'] = df['Waiting_Time'].clip(lower=0)
df['Waiting_Log'] = np.log1p(df['Waiting_Time'])

# ==========================================
# BOX COX TRANSFORMATION
# ==========================================
df['Waiting_Boxcox'], lam = boxcox(
    df['Waiting_Time'] + 1
)
print("\nBOX COX LAMBDA")
print(lam)

# ==========================================
# TRANSFORMATION COMPARISON
# ==========================================

fig, axes = plt.subplots(1,3, figsize=(18,5))

sns.histplot(
    df['Waiting_Time'],
    kde=True,
    ax=axes[0]
)

axes[0].set_title("Original Waiting Time")

sns.histplot(
    df['Waiting_Log'],
    kde=True,
    ax=axes[1]
)

axes[1].set_title("Log Transformation")

sns.histplot(
    df['Waiting_Boxcox'],
    kde=True,
    ax=axes[2]
)

axes[2].set_title("Box-Cox Transformation")

plt.tight_layout()
plt.show()

# ==========================================
# SKEWNESS COMPARISON
# ==========================================

print("\nSKEWNESS COMPARISON")

print(
    "Original:",
    skew(df['Waiting_Time'])
)

print(
    "Log:",
    skew(df['Waiting_Log'])
)

print(
    "Box-Cox:",
    skew(df['Waiting_Boxcox'])
)

# ==========================================
# UNIVARIATE ANALYSIS
# ==========================================

# AGE

plt.figure(figsize=(7,4))
sns.histplot(df['Age'], kde=True)
plt.title("Age Distribution")
plt.show()

# GENDER

plt.figure(figsize=(6,4))
sns.countplot(
    x='Gender',
    data=df
)
plt.title("Gender Distribution")
plt.show()

# NO SHOW

plt.figure(figsize=(6,4))
sns.countplot(
    x='No-show',
    data=df
)
plt.title("No Show Distribution")
plt.show()

# PIE CHART
df['No-show'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)

plt.title("Appointment Attendance")
plt.ylabel("")
plt.show()

# ==========================================
# BIVARIATE ANALYSIS
# ==========================================
# AGE VS NO SHOW
plt.figure(figsize=(7,4))
sns.boxplot(
    x='No-show',
    y='Age',
    data=df
)
plt.title("Age vs No-show")
plt.show()

# GENDER VS NO SHOW

gender_table = pd.crosstab(
    df['Gender'],
    df['No-show']
)

print("\nGENDER VS NO SHOW")
print(gender_table)

# SMS VS NO SHOW

sms_table = pd.crosstab(
    df['SMS_received'],
    df['No-show']
)
print("\nSMS VS NO SHOW")
print(sms_table)

# ==========================================
# VIOLIN PLOT
# ==========================================

plt.figure(figsize=(7,4))
sns.violinplot(
    x='No-show',
    y='Age',
    data=df
)
plt.title("Violin Plot")
plt.show()

# ==========================================
# CORRELATION ANALYSIS
# ==========================================

corr = df.corr(numeric_only=True)

plt.figure(figsize=(10,7))

sns.heatmap(
    corr,
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")
plt.show()

# ==========================================
# CHI SQUARE TEST
# ==========================================

table = pd.crosstab(
    df['Gender'],
    df['No-show']
)

chi2,p,dof,expected = chi2_contingency(table)

print("\nCHI SQUARE TEST")
print("Chi2:",chi2)
print("P-value:",p)

if p < 0.05:
    print("Significant Relationship Exists")
else:
    print("No Significant Relationship")

# ==========================================
# ANOVA TEST
# ==========================================

df['Age_Group'] = pd.cut(
    df['Age'],
    bins=[0,18,60,120],
    labels=['Young','Adult','Senior']
)

young = df[
    df['Age_Group']=='Young'
]['Waiting_Time']

adult = df[
    df['Age_Group']=='Adult'
]['Waiting_Time']

senior = df[
    df['Age_Group']=='Senior'
]['Waiting_Time']

f,p = f_oneway(
    young,
    adult,
    senior
)
print("\nANOVA TEST")
print("F Statistic:",f)
print("P-value:",p)

if p < 0.05:
    print("Waiting Time differs across Age Groups")
else:
    print("No Significant Difference")

# ==========================================
# BUSINESS INSIGHTS
# ==========================================

print("\n" + "="*50)
print("BUSINESS INSIGHTS")
print("="*50)

print(
    "\nNo-show Percentage"
)

print(
    df['No-show']
    .value_counts(normalize=True)
    *100
)

print(
    "\nAverage Waiting Time:"
)

print(
    round(
        df['Waiting_Time'].mean(),
        2
    ),
    "Days"
)

print(
    "\nTop Neighborhoods"
)

print(
    df['Neighbourhood']
    .value_counts()
    .head(10)
)

print(
    "\nSMS Reminder Effectiveness"
)

print(
    pd.crosstab(
        df['SMS_received'],
        df['No-show'],
        normalize='index'
    )*100
)

print("\nPROJECT COMPLETED SUCCESSFULLY")